version: '3.9'

services:

  apache:
    container_name: 3t-web-apache
    image: whosbax/3t-web-apache:dev
    networks:
        backend:
            ipv4_address: 172.20.0.10
    build: './build/apache'
    ports:
      - "8081:80"
    #links:
      #- "php:php_host"     
    command: [ "bash", "-c", "/run.sh" ]        

  nginx:
    container_name: 3t-web-nginx
    image: whosbax/3t-web-nginx:dev  
    environment:
    - NGINX_HOST=whosbax.com
    - NGINX_PORT=80  
    networks:
        backend:
            ipv4_address: 172.20.0.11
    build: './build/nginx'
    depends_on:
      - php
    ports:
      - "8082:80"
    links:
      - "php:php_host"
    command: [ "bash", "-c", "/run.sh" ]       

  php:
    container_name: 3t-web-symfony
    image: whosbax/3t-web-symfony:dev  
    networks:
        backend:
            ipv4_address: 172.20.0.12
    depends_on:
      - mysql
    ports:
      - "9991:9000"
    build: './build/php'
    volumes:
      - ./app:/var/www/
    command: [ "bash", "-c", "/run.sh" ]
    mem_limit: 4096m
    mem_reservation: 2048M
    cpus: 1

  mysql:
    container_name: 3t-web-mysql
    image: mysql
    networks:
        backend:
            ipv4_address: 172.20.0.13
    ports:
      - "3336:3306"
    #command: --init-file /data/application/init.sql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=mysqlrootpass     

networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.0.0/24